/**
 * Pulls Canvas UI components straight out of the shadcn-compatible registry
 * at canvasui.dev and drops them into src/canvasui/ as plain source files.
 *
 * The components are standalone: no Tailwind, no `cn` helper, no registry
 * dependencies, so the whole shadcn init dance is unnecessary here.
 *
 *   node scripts/vendor.mjs            # every component
 *   node scripts/vendor.mjs liquid glass
 */
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "canvasui");
const REGISTRY = "https://canvasui.dev/r/registry.json";

/** Components that pull in three.js — vendored, but flagged so we can note the dep. */
const NEEDS_THREE = new Set([
  "ascii-object",
  "dithered-object",
  "glass-object",
  "liquid-object",
  "particle-object",
]);

const pascal = (slug) =>
  slug.split("-").map((s) => s[0].toUpperCase() + s.slice(1)).join("");

// `--if-missing` is what postinstall uses: already vendored means nothing to do.
if (process.argv.includes("--if-missing") && existsSync(join(OUT, "index.ts"))) {
  console.log("Canvas UI components already vendored — skipping.");
  process.exit(0);
}

const registry = await (await fetch(REGISTRY)).json();

// The registry carries one item per framework; we only want the React ones.
const reactItems = registry.items.filter((i) => i.name.endsWith("-react"));
const wanted = process.argv.slice(2).filter((a) => !a.startsWith("--"));
const targets = wanted.length
  ? reactItems.filter((i) => wanted.includes(i.name.replace(/-react$/, "")))
  : reactItems;

if (!targets.length) {
  console.error("No matching components. Available:");
  console.error(reactItems.map((i) => "  " + i.name.replace(/-react$/, "")).join("\n"));
  process.exit(1);
}

await mkdir(OUT, { recursive: true });

const manifest = [];

await Promise.all(
  targets.map(async (item) => {
    const slug = item.name.replace(/-react$/, "");
    // registry.json omits file contents; the per-item endpoint has them.
    const full = await (await fetch(`https://canvasui.dev/r/${item.name}.json`)).json();
    for (const file of full.files) {
      const name = file.path.split("/").pop();
      await writeFile(join(OUT, name), file.content, "utf8");
    }
    manifest.push({
      slug,
      component: pascal(slug),
      file: full.files[0].path.split("/").pop().replace(/\.tsx?$/, ""),
      title: item.title.replace(/\s*\(React\)$/, ""),
      description: item.description,
      three: NEEDS_THREE.has(slug),
      install: `npx shadcn@latest add @canvas-ui/${item.name}`,
    });
    console.log(`  ✓ ${slug}`);
  }),
);

manifest.sort((a, b) => a.slug.localeCompare(b.slug));

// Static import map so Vite can code-split: only the active effect is fetched.
const loaders = manifest
  .map((m) => `  "${m.slug}": () => import("./${m.file}"),`)
  .join("\n");

await writeFile(
  join(OUT, "index.ts"),
  `// GENERATED by scripts/vendor.mjs — do not edit by hand.
import type { ComponentType, ReactNode } from "react";

export interface EffectMeta {
  slug: string;
  component: string;
  title: string;
  description: string;
  three: boolean;
  install: string;
}

/** Every effect wraps live HTML, so they all take children. */
export type EffectComponent = ComponentType<
  { children: ReactNode; className?: string; style?: React.CSSProperties } & Record<string, unknown>
>;

export const effects: EffectMeta[] = ${JSON.stringify(
    manifest.map(({ file: _file, ...rest }) => rest),
    null,
    2,
  )};

export const loaders: Record<string, () => Promise<{ default: EffectComponent }>> = {
${loaders}
};
`,
  "utf8",
);

const three = manifest.filter((m) => m.three).length;
console.log(
  `\nVendored ${manifest.length} components into src/canvasui/` +
    (three ? ` (${three} need three.js)` : ""),
);
